server:
  port: 7002

spring:
  application:
    name: cloud-eureka-server

eureka:
  instance:
    hostname: eureka7002.com    #eureka服务端实例名称
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例,并不区检索服务
    service-url:
      # 单机版 指向自己
      # defaultZone: http://eureka7002.com:7002/eureka/
      # 集群版 指向其他eureka，注意不是自己
      defaultZone: http://eureka7001.com:7001/eureka/
  #server:
  #  enable-self-preservation: false # 关闭自我保护机制 保证不可用服务及时清除
  #  eviction-interval-timer-in-ms: 2000
